#!/bin/bash
set -ex

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$DIR/../"
VERSION="${VERSION:-opensuse,leap}"
OS_IMAGE="${OS_IMAGE:-suse_os_image.tgz}"

if [ ! -e "$ROOT_DIR/ci/docker/suse-os-image-stemcell-builder/VMware-ovftool-4.1.0-2459827-lin.x86_64.bundle" ];
then
    pushd $ROOT_DIR/ci/docker/suse-os-image-stemcell-builder/
        wget 'https://github.com/richardatlateralblast/ottar/raw/master/VMware-ovftool-4.1.0-2459827-lin.x86_64.bundle'
    popd
fi

docker build $ROOT_DIR/ci/docker/suse-os-image-stemcell-builder/ -t bosh/suse-os-image-stemcell-builder

docker run --rm --privileged \
                -e "VERSION=$VERSION" \
                -e "FILE=$OS_IMAGE" \
                -e LOCAL_USER_ID=$(id -u "$USER") \
                -v $ROOT_DIR/build:/opt/bosh/tmp \
                -v "$ROOT_DIR:/opt/bosh" \
                --workdir /opt/bosh \
                -t -i bosh/suse-os-image-stemcell-builder \
                make deps build
